# Generated by Django 5.2.5 on 2025-08-19 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ims', '0002_purchase_supplier_purchaseitem_purchase_supplier'),
    ]

    operations = [
        migrations.AddField(
            model_name='supplier',
            name='is_available',
            field=models.CharField(choices=[('A', 'Available'), ('N', 'Not Available')], default='A', max_length=1),
        ),
    ]
