# Generated by Django 5.2.5 on 2025-09-05 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='phone_number',
            field=models.CharField(default=9800000000, max_length=15),
            preserve_default=False,
        ),
    ]
